device: null
logger:
  backend: wandb
  project_name: torchrl_pilco
  group_name: null
pilco:
  horizon: 40
  initial_rollout_length: 200
  max_rollout_length: 500
  epochs: 15
  policy_training_steps: 100
  policy_n_basis: 30
  eval_max_steps: 200
  initial_state_var: 1e-2
  policy_restarts: 3
  target: [1.0, 0.0, 0.0]
  weights: [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 0.0]]
